package cliente.hilos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author daniel
 */
public class VentanaHilos extends javax.swing.JFrame {

    Hilo hilo1;
    Hilo hilo2;
    Hilo hilo3;
    
    /**
     * Creates new form VentanaHilos
     */
    public VentanaHilos() {
        initComponents();
        this.hilo1 = new Hilo("Hilo 1", 100, new Writer(jList1));
        this.hilo2 = new Hilo("Hilo 2", 300, new Writer(jList2));
        this.hilo3 = new Hilo("Hilo 3", 500, new Writer(jList3));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIniciar = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jScrollPane1 = new JScrollPane();
        jList1 = new JList<>();
        jScrollPane2 = new JScrollPane();
        jList2 = new JList<>();
        jScrollPane3 = new JScrollPane();
        jList3 = new JList<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio");

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("Hilo 1");

        jLabel2.setText("Hilo 2");

        jLabel3.setText("Hilo 3");

        jList1.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new DefaultListModel<String>());
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new DefaultListModel<String>());
        jScrollPane3.setViewportView(jList3);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIniciar)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIniciar)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
        DefaultListModel listModel1 = (DefaultListModel) jList1.getModel();
        listModel1.removeAllElements();
        
        DefaultListModel listModel2 = (DefaultListModel) jList2.getModel();
        listModel2.removeAllElements();
        
        DefaultListModel listModel3 = (DefaultListModel) jList3.getModel();
        listModel3.removeAllElements();
        
        Thread t1 = new Thread(hilo1);
        t1.start();
        Thread t2 = new Thread(hilo2);
        t2.start();
        Thread t3 = new Thread(hilo3);
        t3.start();
        
        this.jButtonIniciar.setEnabled(false);
        new Thread(() -> {
            while (true) {
                if (!t1.isAlive() && !t2.isAlive() && !t3.isAlive()) {
                    this.jButtonIniciar.setEnabled(true);
                    break;
                }
                try {
                    Thread.currentThread().sleep(100);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
        }).start();
        
        
    }//GEN-LAST:event_jButtonIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonIniciar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JList<String> jList1;
    private JList<String> jList2;
    private JList<String> jList3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
